name: clojure fmt
on:
  pull_request:
    branches: [main]
jobs:
  clojure-fmt:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: bltavares/actions/cljfmt@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: autofix src
