name: clojure fmt
on:
  pull_request:
    branches: [main]
jobs:
  clojure-fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: bltavares/actions/cljfmt@1.0.8
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: check src
