name: Clojure linting

on:
    push
jobs:
  clojure-fmt:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: bltavares/actions/cljfmt@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: lint src

  clj-kondo:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: DeLaGuardo/clojure-lint-action@master
        with:
          clj-kondo-args: --lint src
          github_token: ${{ secrets.GITHUB_TOKEN }}
